module.exports = [
  'http://ajoogle0001.esy.es',
  'https://buckish-fall.000webhostapp.com',
  'https://pitogoadones.000webhostapp.com',
  'https://cathrineflings.000webhostapp.com',
  'https://ambitionless-elapse.000webhostapp.com',
  'https://danielmbo.000webhostapp.com',
  'https://shellshocked-fur.000webhostapp.com',
  'https://anamnestic-subrouti.000webhostapp.com',
  'https://intuitionist-overco.000webhostapp.com',
  'https://unimportant-splitte.000webhostapp.com',
  'https://biliary-supermarket.000webhostapp.com',
  'http://three3.hol.es',
  'https://guest-subprogram.000webhostapp.com',
  'https://unauthorised-sugar.000webhostapp.com',
]